name: Publish Docker image to GHCR

on:
  push:
    branches: [ "master", "main", "helm" ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/sec-issue-bot
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Bump pod rollout annotation in values.yaml
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: mikefarah/yq@v4
        with:
          cmd: yq -i '.podAnnotations.rolloutTimestamp = strenv(GITHUB_SHA)' charts/sec-issue-bot/values.yaml

      - name: Commit and push rollout bump
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if git diff --quiet --exit-code charts/sec-issue-bot/values.yaml; then
            echo "No changes to commit"
            exit 0
          fi
          git add charts/sec-issue-bot/values.yaml
          git commit -m "ci: force rollout via podAnnotations.rolloutTimestamp=${GITHUB_SHA} [skip ci]"
          git push

