name: Publish Docker image to GHCR

on:
  # Gate publish on CI success on main branch
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  build-and-push:
    # Only run after CI succeeded on main
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: prep
        shell: bash
        run: |
          SHORT_SHA=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${OWNER_LC}/sec-issue-bot" >> $GITHUB_ENV
          echo "TAGS=ghcr.io/${OWNER_LC}/sec-issue-bot:sha-${SHORT_SHA},ghcr.io/${OWNER_LC}/sec-issue-bot:latest" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.TAGS }}
          labels: org.opencontainers.image.revision=${{ github.event.workflow_run.head_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Bump pod rollout annotation in values.yaml
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: mikefarah/yq@v4
        with:
          cmd: yq -i '.podAnnotations.rolloutTimestamp = strenv(GITHUB_SHA)' charts/sec-issue-bot/values.yaml

      - name: Commit and push rollout bump
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if git diff --quiet --exit-code charts/sec-issue-bot/values.yaml; then
            echo "No changes to commit"
            exit 0
          fi
          git add charts/sec-issue-bot/values.yaml
          git commit -m "ci: force rollout via podAnnotations.rolloutTimestamp=${GITHUB_SHA} [skip ci]"
          git push

